runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: website/index.htm
  upload: website/index.htm
  secure: always
  http_headers: 
    Strict-Transport-Security: 'max-age=63072000; includeSubDomains; preload'

- url: /
  static_dir: website

